"""
app.py — Streamlit demo app for ML Assignment 2.

Required features implemented:
  a. CSV upload for test data
  b. Model selection dropdown
  c. Display of evaluation metrics
  d. Confusion matrix / classification report

Run locally with:  streamlit run app.py
"""

from pathlib import Path

import joblib
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import streamlit as st
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.preprocessing import label_binarize

st.set_page_config(page_title="Mobile Price Classifier — Model Comparison", layout="wide")

MODEL_DIR = Path("model")
TARGET_COL = "price_range"  # must match train_models.py

# Friendly display names for the 5 required models (falls back to a
# title-cased filename for anything else found in model/)
NICE_NAMES = {
    "logistic_regression": "Logistic Regression",
    "decision_tree": "Decision Tree",
    "knn": "kNN",
    "naive_bayes": "Naive Bayes",
    "random_forest": "Random Forest",
}


@st.cache_resource
def load_models():
    """Load every .joblib pipeline found in model/ into a {display_name: model} dict."""
    models = {}
    if not MODEL_DIR.exists():
        return models
    for f in sorted(MODEL_DIR.glob("*.joblib")):
        display_name = NICE_NAMES.get(f.stem, f.stem.replace("_", " ").title())
        models[display_name] = joblib.load(f)
    return models


def compute_metrics(model, X, y):
    """Returns (metrics_dict, y_pred). Handles binary vs multi-class AUC automatically."""
    classes = sorted(y.unique())
    y_pred = model.predict(X)
    y_proba = model.predict_proba(X)

    if len(classes) > 2:
        y_bin = label_binarize(y, classes=classes)
        auc = roc_auc_score(y_bin, y_proba, average="weighted", multi_class="ovr")
    else:
        auc = roc_auc_score(y, y_proba[:, 1])

    metrics = {
        "Accuracy": accuracy_score(y, y_pred),
        "AUC": auc,
        "Precision": precision_score(y, y_pred, average="weighted", zero_division=0),
        "Recall": recall_score(y, y_pred, average="weighted", zero_division=0),
        "F1": f1_score(y, y_pred, average="weighted", zero_division=0),
        "MCC": matthews_corrcoef(y, y_pred),
    }
    return metrics, y_pred


def render_confusion_matrix(y_true, y_pred, ax, title=None):
    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", ax=ax, cbar=False)
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")
    if title:
        ax.set_title(title, fontsize=10)


def main():
    st.title("📱 Mobile Price Classification — Model Comparison Dashboard")
    st.caption("BITS Pilani WILP — M.Tech (AIML/DSE) — Machine Learning, Assignment 2")

    models = load_models()
    if not models:
        st.error(
            "No trained models found in the 'model/' folder. Run train_models.py first "
            "and make sure the resulting model/*.joblib files are committed to this repo."
        )
        return

    st.sidebar.header("1. Upload test data")
    uploaded = st.sidebar.file_uploader(
        "Upload a CSV (must include the true label column)", type=["csv"]
    )

    st.sidebar.header("2. Choose a model")
    model_choice = st.sidebar.selectbox("Model", list(models.keys()) + ["Compare all models"])

    if uploaded is None:
        st.info(
            "⬅️ Upload a test CSV from the sidebar to get started. "
            "Use the test_data.csv generated by train_models.py."
        )
        return

    df = pd.read_csv(uploaded)

    if TARGET_COL not in df.columns:
        st.error(
            f"Uploaded file must contain the '{TARGET_COL}' column (the true label) "
            f"so metrics can be computed. Columns found: {list(df.columns)}"
        )
        return

    X = df.drop(columns=[TARGET_COL])
    y = df[TARGET_COL]

    st.subheader("Preview of uploaded data")
    st.dataframe(df.head(), use_container_width=True)

    if model_choice == "Compare all models":
        st.subheader("📊 Evaluation Metrics — All Models")
        rows = {}
        preds = {}
        for name, model in models.items():
            metrics, y_pred = compute_metrics(model, X, y)
            rows[name] = metrics
            preds[name] = y_pred
        comp_df = pd.DataFrame(rows).T.round(4)
        st.dataframe(comp_df, use_container_width=True)

        st.subheader("Confusion matrices")
        cols = st.columns(len(models))
        for col, (name, y_pred) in zip(cols, preds.items()):
            fig, ax = plt.subplots(figsize=(3, 3))
            render_confusion_matrix(y, y_pred, ax, title=name)
            col.pyplot(fig)
            plt.close(fig)
    else:
        model = models[model_choice]
        metrics, y_pred = compute_metrics(model, X, y)

        st.subheader(f"📊 Evaluation Metrics — {model_choice}")
        metric_cols = st.columns(len(metrics))
        for col, (k, v) in zip(metric_cols, metrics.items()):
            col.metric(k, f"{v:.4f}")

        c1, c2 = st.columns(2)
        with c1:
            st.subheader("Confusion Matrix")
            fig, ax = plt.subplots()
            render_confusion_matrix(y, y_pred, ax)
            st.pyplot(fig)
            plt.close(fig)

        with c2:
            st.subheader("Classification Report")
            report = classification_report(y, y_pred, output_dict=True, zero_division=0)
            report_df = pd.DataFrame(report).transpose().round(3)
            st.dataframe(report_df, use_container_width=True)


if __name__ == "__main__":
    main()
